import Head from 'next/head'
import Image from 'next/image'
import { Card } from '../components/Card'
import { CustomNodeFlow, FlowStarter } from '../components/Flow'
import { FlowContainer } from '../components/Flow/FlowContainer.styled'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FlowContainer style={{ height: "100vh", width: "100%", border: "1px solid black" }}>
          <FlowStarter />
        </FlowContainer>
        <FlowContainer style={{ height: "100vh", width: "100%", border: "1px solid black" }}>
          <CustomNodeFlow />
        </FlowContainer>
        {/* <OverviewFlow /> */}
        <Card />
        {/* <Flow /> */}
        <div className="card card--sensor">
          <div className="card__title">Sensor</div>
          <div className="card__type">
            <p>Type</p>
            <input type="text"></input>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
